apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  HF_TOKEN: {{ .Values.secrets.hfToken | quote }}
  ACCESS_TOKEN: {{ .Values.secrets.accessToken | quote }}
  INFERENCE_API_KEY: {{ .Values.secrets.inferenceApiKey | quote }}
  AUTH_BOOTSTRAP_PASSWORD: {{ .Values.secrets.authBootstrapPassword | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secrets.minioAccessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.secrets.minioSecretKey | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.minioAccessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.minioSecretKey | quote }}
  GF_SECURITY_ADMIN_USER: {{ .Values.secrets.grafanaAdminUser | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | quote }}
