{% if cookiecutter.use_monitoring == "yes" %}
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: {{ cookiecutter.namespace }}
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: {{ cookiecutter.nodeport_grafana }}
---
{% endif %}
apiVersion: v1
kind: Service
metadata:
  name: mlflow-nodeport
  namespace: {{ cookiecutter.namespace }}
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: {{ cookiecutter.nodeport_mlflow }}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-api-nodeport
  namespace: {{ cookiecutter.namespace }}
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: {{ cookiecutter.nodeport_minio_api }}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console-nodeport
  namespace: {{ cookiecutter.namespace }}
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: {{ cookiecutter.nodeport_minio_console }}
