apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-core-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BiirCommunity/mlops-core.git
    targetRevision: main
    path: deploy/helm/mlops-secrets
    helm:
      parameters:
        - name: secrets.hfToken
          value: ""
        - name: secrets.accessToken
          value: changeme-set-strong-token
        - name: secrets.inferenceApiKey
          value: changeme-set-inference-api-key
        - name: secrets.authBootstrapPassword
          value: changeme-admin
        - name: secrets.minioAccessKey
          value: minioadmin
        - name: secrets.minioSecretKey
          value: minioadmin
        - name: secrets.grafanaAdminUser
          value: admin
        - name: secrets.grafanaAdminPassword
          value: admin
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
