apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-core
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - group: batch
      kind: Job
      name: minio-init
      jsonPointers:
        - /status
  source:
    repoURL: https://github.com/BiirCommunity/mlops-core.git
    targetRevision: main
    path: k8s
    kustomize:
      images:
        - ghcr.io/biircommunity/mlops-core-app:latest
        - ghcr.io/biircommunity/mlops-core-auth-service:latest
        - ghcr.io/biircommunity/mlops-core-admin-ui:latest
        - ghcr.io/biircommunity/mlops-core-chat-ui:latest
        - ghcr.io/biircommunity/mlops-core-mlflow:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
