apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-core-no-gpu
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/BiirCommunity/mlops-core.git
    targetRevision: main
    path: k8s/overlays/no-gpu
    kustomize:
      images:
        - mlops-core-app=ghcr.io/biircommunity/mlops-core-app:latest
        - mlops-core-auth-service=ghcr.io/biircommunity/mlops-core-auth-service:latest
        - mlops-core-admin-ui=ghcr.io/biircommunity/mlops-core-admin-ui:latest
        - mlops-core-chat-ui=ghcr.io/biircommunity/mlops-core-chat-ui:latest
        - mlops-core-mlflow=ghcr.io/biircommunity/mlops-core-mlflow:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
