apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-ui
  namespace: mlops
  labels:
    app: chat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-ui
  template:
    metadata:
      labels:
        app: chat-ui
    spec:
      containers:
        - name: chat-ui
          image: mlops-core-chat-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 64Mi
            limits:
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: chat-ui
  namespace: mlops
spec:
  selector:
    app: chat-ui
  ports:
    - port: 8080
      targetPort: 8080
